name: Zesty Website CI Dev
on:
  pull_request:
    branches: [stage,accounts,production,dev]
  workflow_dispatch:
jobs:
  build-check:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: 'false'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup custom host for mylocal
        run: echo "127.0.0.1 test.zesty.io" | sudo tee -a /etc/hosts

      - name: Install dependencies 
        run: npm ci

      - name: Check format and linters
        run: npm run test-all

      - name: Build Project 
        run: npm run build
