name: Zesty Website E2E Test
on:
  pull_request:
    branches: [production,stage]
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: 'false'
    steps:
      - uses: actions/checkout@v3

      - name: Setup custom host for mylocal
        run: echo "127.0.0.1 test.zesty.io" | sudo tee -a /etc/hosts

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
         path: ~/.npm
         key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
         restore-keys: npm-${{ runner.os }}-

      - name: Install dependencies 
        run: npm install

      - name: Build Project 
        run: npm run build

      - name: Website routes E2E test 
        run: npm run test
