name: Zesty Website E2E Test
on:
  pull_request:
    branches: [production,stage]
  workflow_dispatch:
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: 'false'
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Setup custom host for mylocal
        run: echo "127.0.0.1 test.zesty.io" | sudo tee -a /etc/hosts

      - name: Install dependencies 
        run: bun install

      - name: Build Project 
        run: bun run build

      - name: Website routes E2E test 
        run: bun run test
