on:
  pull_request:
    types: [opened, synchronize, edited]
    branches: [stage, accounts, production, dev]
  workflow_dispatch:

jobs:
  pr_lint:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
